version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
- Debug
init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd verify
build:
  parallel: true
  verbosity: minimal