version: 1.0.{build}
os: Visual Studio 2015
configuration:
- Release
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  parallel: true
  verbosity: minimal